"""Make teacher_school_record_id nullable

Revision ID: 3884645c4fcf
Revises: 
Create Date: 2025-12-07 02:59:14.275560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3884645c4fcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avator_fileupload', schema=None) as batch_op:
        batch_op.alter_column('student_school_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('teacher_school_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # Give a name to the unique constraint
        batch_op.create_unique_constraint('uq_avator_student_school_record', ['student_school_record_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avator_fileupload', schema=None) as batch_op:
        batch_op.drop_constraint('uq_avator_student_school_record', type_='unique')
        batch_op.alter_column('teacher_school_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_school_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
