"""Add columns to assignments models

Revision ID: 910e28658fa0
Revises: 3884645c4fcf
Create Date: 2025-12-07 13:25:32.607242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910e28658fa0'
down_revision = '3884645c4fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issued_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignment_submission', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('issued_date')

    # ### end Alembic commands ###
